# Generated by Django 3.1 on 2020-11-04 20:34

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cache_Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('current_rendition', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='Failure_Cause',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('failure_mode', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Product_Id',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prod_id', models.CharField(max_length=32)),
                ('description', models.CharField(max_length=128)),
                ('unit_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('unit', models.CharField(max_length=32)),
                ('date_updated', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=32)),
                ('password', models.CharField(max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Scrap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField(default=django.utils.timezone.now)),
                ('total_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('units_scrapped', models.IntegerField()),
                ('failure', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='failure', to='scrap_backend.failure_cause')),
                ('prod_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap_backend.product_id')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scrap_user', to='scrap_backend.user')),
            ],
        ),
        migrations.CreateModel(
            name='Refresh_Token',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=128)),
                ('time_created', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap_backend.user')),
            ],
        ),
        migrations.AddField(
            model_name='product_id',
            name='updating_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updating_user', to='scrap_backend.user'),
        ),
        migrations.AddField(
            model_name='failure_cause',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='scrap_backend.product_id'),
        ),
    ]
