# Generated by Django 3.1 on 2020-11-17 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_backend', '0003_scrap_lot_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClosedScrapComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=128)),
                ('scrap', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scrap_backend.scrap')),
            ],
        ),
    ]
