# Generated by Django 3.1.4 on 2020-12-09 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrap_backend', '0004_closedscrapcomments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cache_Token',
            new_name='CacheToken',
        ),
        migrations.RenameModel(
            old_name='Failure_Cause',
            new_name='FailureCause',
        ),
        migrations.RenameModel(
            old_name='Product_Id',
            new_name='ProductId',
        ),
        migrations.RenameModel(
            old_name='Refresh_Token',
            new_name='RefreshToken',
        ),
    ]
